name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          mkdir -p $HOME/.aws
          echo "[default]" >> $HOME/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> $HOME/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> $HOME/.aws/credentials
          echo "[default]" >> $HOME/.aws/config
          echo "region = us-east-1" >> $HOME/.aws/config

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 481510018989.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1

      - name: Build and push Docker image
        run: |
          docker build -t 481510018989.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1:latest .
          docker push 481510018989.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1:latest
