name: Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./clo835_summer2023_assignment1-main
          file: ./clo835_summer2023_assignment1-main/Dockerfile
          push: true
          tags: 481510018989.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1:latest
