name: Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Define environment variables for all steps
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # Include this only if you're using temporary security credentials

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, test, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: clo835_assignment1
        run: |
          # Building MySQL Docker image
          docker build -t my_db -f Dockerfile_mysql .
          # Tagging MySQL Docker image
          docker tag my_db $ECR_REGISTRY/$ECR_REPOSITORY:mysql
          # Pushing MySQL Docker image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:mysql

          # Building Application Docker image
          docker build -t my_app -f Dockerfile .
          # Tagging Application Docker image
          docker tag my_app $ECR_REGISTRY/$ECR_REPOSITORY:application
          # Pushing Application Docker image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:application
