name: Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Image 1
        uses: docker/build-push-action@v2
        with:
          context: ./path_to_image1_context
          file: ./path_to_image1_dockerfile
          push: true
          tags: 481510018989.dkr.ecr.us-east-1.amazonaws.com/image1:latest

      - name: Build and push Image 2
        uses: docker/build-push-action@v2
        with:
          context: ./path_to_image2_context
          file: ./path_to_image2_dockerfile
          push: true
          tags: 481510018989.dkr.ecr.us-east-1.amazonaws.com/image2:latest
