name: Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Define environment variables for all steps
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # Include this only if you're using temporary security credentials

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./ # Change this to match your Dockerfile location
          file: Dockerfile # Change this to match your Dockerfile location
          push: true
          tags: 481510018989.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1:latest
